# Generated by Django 4.2.11 on 2024-05-02 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_alter_blog_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like_user',
            field=models.ManyToManyField(related_name='like_blog', to=settings.AUTH_USER_MODEL),
        ),
    ]
