# Generated by Django 4.2.11 on 2024-04-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(null=True, to='blog.tag'),
        ),
    ]
